pishifat/qat

- routes/bnApp.js
> remove the line

- src/components/evaluations/info/FeedbackPm.vue
- adds more helpful links to acceptance feedback pms
- tries to emphasize a bit more on rejection pms that users can ask for additional feedback (yes)
i pray to the lord i did this right cause i have no idea how to write .vue files and just guessed my way through it
> Update feedback pms

- src/components/FilterBox.vue
- src/components/vetoes/SubmitVeto.vue
- src/components/vetoes/VetoCard.vue
- src/components/vetoes/VetoInfo.vue
- src/components/vetoes/info/ConclusionPost.vue
- src/components/vetoes/info/ForumPm.vue
- src/components/vetoes/info/MediationInput.vue
- src/components/vetoes/info/Mediations.vue
- src/components/vetoes/info/ModalBody.vue
- src/components/vetoes/info/ModalFooter.vue
- src/components/vetoes/info/ModalHeader.vue
- src/pages/VetoesPage.vue
- split VetoInfo into separate components 
- some code improvements :eyes:
> vetoes refactor

- src/mixins/filterLinks.js
also converted string connections to ES6 syntax :eyes:
> Add BBCode url tag support to filterLinks mixin

- app.js
- config.example.json
- routes/interOp.js
0 testing so i hope this works 🙏 🎉 🌮 🌮🌮💯 🔢 🧠
> Add interop routes for user listing and mapset QA

- src/components/evaluations/info/Evaluations.vue
> use proper content-type for evals from bns

- src/components/evaluations/info/common/EvaluatorAssignments.vue
> Remove duplicate line breaks from selecting BN evaluators template

- helpers/notifications.js
#22 with changes and without conflicts
> handle reopens in reportfeed

- helpers/scrap.js
- routes/bnApp.js
- routes/index.js
- routes/users/users.js
- src/components/home/ModScoreCalculator.vue
- views/index.hbs
- use the oauth2 endpoint instead of scraping html
- use maps instead of arrays for containers being used as sets
- v-for to generate text boxes
> minor improvements to mod score calculator

- routes/modRequests/submissions.js
- src/components/modRequests/EditRequestModal.vue
- src/components/modRequests/MyRequestRow.vue
- src/components/modRequests/RequestRow.vue
- src/pages/ModRequestsSubmission.vue
- src/store/modRequests.js
- Allows a user to edit their own requests
- Show # of BNs who denied
- Show category to requester
- Reformat time and add original date on hover
> Mod requests page minor improvements

- routes/evaluations/appEval.js
- routes/users/users.js
- src/App.vue
- src/components/BotChatMessage.vue
- src/components/evaluations/info/common/EvaluatorAssignments.vue
- src/components/settingsModal/SettingsModalEvaluator.vue
- src/components/settingsModal/SettingsModalModeEvaluations.vue
- src/components/users/info/BnEvaluatorToggle.vue
- src/components/users/info/TrialNatToggle.vue
"BN evaluator" -> "Mock evaluations"
"Trial NAT" -> "BN Evaluator"
hopefully i didn't miss anything
frontend only because updating backend isn't worth it, GL pishi with not mixing up both in the future lmfao
> we suck at naming things

- shared/enums.js
Was requested by RandomeLoL in dev server.
> Adding Catalan to `enums.js`

- helpers/util.js
- routes/evaluations/evaluations.js
> add automatic timestamp conversion in feedback

- routes/bnApp.js
- src/pages/ApplicationSubmission.vue
lmk if i did something wrong, first time dabbling with state in vue
> allow new applicants so submit only 3 mods

- README.md
- app.js
- config.example.json
- helpers/middlewares.js
- models/user.js
- routes/debug.js
- routes/evaluations/appEval.js
- routes/index.js
- routes/users/nat.js
- src/App.vue
- src/components/debugModal/DebugModal.vue
- src/components/debugModal/DebugModalPermissions.vue
- src/components/evaluations/info/common/EvaluationIsReviewed.vue
- src/sass/_variables.scss
to make things easier, I've made it so pishi's osu! id and `isResponsibleWithButtons` osu! ids are no longer hardcoded so it's easy to control access to certain stuff, basically add/edit the `admin` object in `config.json` with the appropriate userids. check out`config.example.json` for reference
debug menu only controls your site permissions right now, but it shouldn't be hard to add new stuff in. it's a pishi-only menu btw
> add debug menu + some refactoring

- .gitignore
- helpers/discord.js
- helpers/notifications.js
- helpers/osuBot.js
- routes/discussionVote.js
- routes/evaluations/appEval.js
- routes/evaluations/bnEval.js
- routes/manageReports.js
- routes/vetoes.js
- src/components/BotChatMessage.vue
- src/components/evaluations/info/applications/EnableBnEvaluatorsChatMessage.vue
- src/components/evaluations/info/common/FeedbackPm.vue
- src/components/reports/info/ReportFeedbackPm.vue
- src/components/vetoes/VetoChatMessage.vue
finally 🙃 
okso things *should* be working as long as your `getBotToken()` function works [here](https://github.com/pishifat/qat/pull/149/files#diff-61f98e3aaec6f5921aa20549026edefbb403a09815302ad9b15f8477d2909ebcR93), which i couldn't test properly because of lack of resources (dont have a chat bot in announce usergroup, kept getting a 400 Bad Request error), so you'd have to test manually with the mappersguild bot
fwiw i tested by manually getting an access token thru an external script that uses authorization code grant
> convert message system to chat announcements

- src/App.vue
- src/routes.js
page is already public, doesn't hurt to make it accessible via navbar as mentioned in internal
> add /testresults to navbar

- helpers/discord.js
- add 1st image to embed
- add spaces between roles
- replace all image links `![](LINK)` with `[image](LINK)` (only in the embed) cuz cleaner
> announcement embed cleanup

- app.js
- helpers/websocket.js
- src/pages/ModRequests.vue
> add pings to websockets

- models/interfaces/user.ts
- models/user.js
- routes/index.js
- src/components/home/UserCard.vue
currently being used by homepage user cards, may be used for future redesigns
> add user covers to user document

- src/components/evaluations/card/EvaluationCard.vue
- src/components/evaluations/info/ArchiveInfo.vue
- src/components/evaluations/info/DiscussionInfo.vue
- src/components/evaluations/info/EvaluationInfo.vue
- src/components/evaluations/info/YourEvalsInfo.vue
- src/components/evaluations/info/common/EvaluationLink.vue
- src/components/users/UserInfo.vue
apart from commit names this also fixes a bug where archive cards abt regular users don't have a triangles bg
> a bunch of qol stuff

- src/components/users/UserInfo.vue
> allow adding notes on former members

- routes/evaluations/evaluations.js
- routes/users/nat.js
> better nat eval embeds

- helpers/automation.js
> ping both leaders

- routes/users/users.js
- src/components/ModeRadioDisplay.vue
- src/components/users/Badges.vue
- src/components/users/PotentialNatInfo.vue
- src/components/users/UserInfo.vue
- src/components/users/info/FormerUserGroupToggle.vue
- src/pages/UsersPage.vue
made the button red to better signify its a dangerous action
> add `move to nat` toggle for former users

- src/sass/_variables.scss
- src/sass/app.scss
mg has this cool selection color so i thought i'd add something similar here
> add selection colors

- src/components/users/UserInfo.vue
> show notes for active users again

- README.md
- helpers/websocket.js
- routes/dataCollection.js
needed for aiess
this pr should additionally serve as a guide on how to implement websocket support for events
> report sev events via websocket

- helpers/discord.js
- models/log.js
- routes/evaluations/appEval.js
- routes/evaluations/bnEval.js
- routes/index.js
- routes/interOp.js
- routes/logs.js
- src/pages/Logs.vue
- src/routes.js
logs namechanges made by users in more than 1 group (aka bn/nat/gmt) for now
> implement public logs

- README.md
- package-lock.json
- package.json
- src/app.js
- src/pages/AppEvalPage.vue
- src/pages/ApplicationSubmission.vue
- src/pages/BnEvalPage.vue
- src/pages/DataCollectionPage.vue
- src/pages/DiscussionVotePage.vue
- src/pages/EvalArchivePage.vue
- src/pages/Home.vue
- src/pages/Logs.vue
- src/pages/ManageReportsPage.vue
- src/pages/ManageTestPage.vue
- src/pages/MessagePage.vue
- src/pages/NotFound.vue
- src/pages/QualityAssurancePage.vue
- src/pages/ReportSubmission.vue
- src/pages/Spam.vue
- src/pages/TestResultsPage.vue
- src/pages/TestSubmissionPage.vue
- src/pages/UsersPage.vue
- src/pages/VetoesPage.vue
- src/pages/YourEvalsPage.vue
tried making a few of them dynamic but i lost all my hair, maybe another day
preview (they are all similar) (feel free to revert https://github.com/pishifat/qat/pull/187/commits/eca03fad1bc9afbcc50fdf0698b36b8bd9a948c4 if you dont like it)
> add opengraph headers for embeds

- routes/discussionVote.js
- routes/reports.js
was gonna block specific links but they all have `ppy.sh` so i figured blocking that is easier
also puu.sh cuz files self delete rather quickly
> block more links from cr/reports

- package-lock.json
- package.json
- src/app.js
- src/pages/AppEvalPage.vue
- src/pages/ApplicationSubmission.vue
- src/pages/BnEvalPage.vue
- src/pages/DataCollectionPage.vue
- src/pages/DiscussionVotePage.vue
- src/pages/EvalArchivePage.vue
- src/pages/Home.vue
- src/pages/Logs.vue
- src/pages/ManageReportsPage.vue
- src/pages/ManageTestPage.vue
- src/pages/MessagePage.vue
- src/pages/NotFound.vue
- src/pages/QualityAssurancePage.vue
- src/pages/ReportSubmission.vue
- src/pages/Spam.vue
- src/pages/TestResultsPage.vue
- src/pages/TestSubmissionPage.vue
- src/pages/UsersPage.vue
- src/pages/VetoesPage.vue
- src/pages/YourEvalsPage.vue
> it did not work

- routes/discussionVote.js
- routes/reports.js
- src/components/evaluations/info/EvaluationInfo.vue
- src/components/evaluations/info/common/EvaluationIsSecurityChecked.vue
- src/components/users/UserInfo.vue
- src/components/users/info/Notes.vue
- src/pages/ApplicationSubmission.vue
most notably:
- fuju requested to hide notes behind a collapse menu to reduce the amount of used up space (esp for nats cuz they get +1 note each month)
- randome requested that /bnapps should clearly show that osu! is the default mode by highlighting its mode icon
- also took the opportunity to add a warning that mentions the mode you're applying for, because the amount of ppl accidentally applying for the wrong mode this year is 3 which is more than 0 (they are all taiko people) (my mode) (ashamed)
- maxus reported an issue with sec check button not working on mobile, turns out that was because tooltip was too big
- fuju reported that rejoin button doesnt work on initial load unless you switch modes, fixed that by loading `relevantResignation` of default mode on page creation
> some more qol fixes

- src/pages/UsersPage.vue
helps a lot with directly opening a user card using a link from memory instead of having to open /users and use manual lookup, will be more useful in the near future methinks
> implement username and osuId queries for /users

- helpers/automation.js
- helpers/discord.js
- routes/evaluations/appEval.js
- routes/index.js
- src/components/discussion/info/DiscussionContext.vue
- src/pages/EvalArchivePage.vue
- src/pages/YourEvalsPage.vue
if a nat sets consensus to pass, they get pinged, if it's a non-nat, then a random nat from reviewers gets pinged
other commits should be self-explanatory
> ping relevant nat for sec checks + other minor fixes

- src/app.js
n-th time's the charm
okso last time i made 2 distinct fuckups:
1. used correct attributes, but `vue-meta` didn't work
2. after that, used wrong attributes with my more direct approach + it was lacking extra work
i basically rewrote point 2
> redo opengraph meta tag handling

- src/app.js
- views/index.hbs
ok im done with opengraph stuff, this apparently needs server side rendering and its not worth reworking the entire project just for this lmaoooo
> use static opengraph headers

- src/components/dataCollection/EventsTable.vue
- src/components/evaluations/info/currentBns/userActivity/NominationResets.vue
- src/components/reports/info/ModalHeader.vue
finding all the places where this happens, the exact elements to fix, and the necessary css fix was more annoying than one would think
> fix text overflow in some elements

- helpers/webhookConfig.js
seeing if forcing a proper file read would fix config loading issues
> read config directly

- helpers/discord/getRoles.js
- helpers/discord/getWebhook.js
- helpers/webhookConfig.js
forces a reload and a fresh fetch on each webhook call
> webhook fix attempt #2

- routes/evaluations/bnEval.js
- routes/users/users.js
always felt weird that those are the only types of evals that dont have pings
> ping evalers in resignations and manual evals

- models/interfaces/user.ts
- models/user.js
- routes/evaluations/appEval.js
- routes/users/users.js
- src/components/home/UserInfo.vue
> show last date opened for requests

- app.js
- helpers/automation.js
- models/interfaces/user.ts
- models/user.js
- routes/discussionVote.js
- routes/users/users.js
- src/components/discussion/SubmitDiscussion.vue
- src/components/home/UserCard.vue
- src/components/settingsModal/SettingsModal.vue
- src/components/settingsModal/SettingsModalContentReview.vue
- src/pages/ApplicationSubmission.vue
- src/pages/Home.vue
- src/pages/ReportSubmission.vue
cleaned up homepage user card based on feedback
added CR opt-in for nat/gmt, they can toggle that + assign their discord ids and they'll be pinged individually for each cr creation/reminder
pings for when a content review is close to deadline and doesnt have enough votes 
force user to check if a submission is a video, and to provide timestamps if true
> bunch of stuff

- src/components/ModeDisplay.vue
- src/components/users/UserCard.vue
- src/pages/ApplicationSubmission.vue
> better bn application ux

- helpers/automation.js
- src/components/users/Badges.vue
went with the easier route to updating this
> account for new bn/nat badges

- routes/index.js
- src/components/users/UserInfo.vue
- src/components/users/info/ContentReviewToggle.vue
so people stop getting pinged when they are no longer nat/gmt
> cr toggle for former users

- src/components/ModeSelect.vue
- src/components/evaluations/info/currentBns/Impact.vue
- src/components/evaluations/info/currentBns/userActivity/UserActivity.vue
- src/pages/ApplicationSubmission.vue
> occasional qol pr

- app.js
- helpers/middlewares.js
- routes/groupHistory.js
- src/App.vue
- src/bootstrap.js
- src/components/ModeDisplay.vue
- src/pages/GroupHistoryPage.vue
- src/pages/Logs.vue
- src/routes.js
osu-web one aint getting added anytime soon so we gotta make do
> add group history page

- src/components/users/UserInfo.vue
- src/pages/GroupHistoryPage.vue
- src/store/users.js
a couple of qol stuff i wanted for a while but kept forgetting about
> former bn info improvements

- README.md
- helpers/websocket.js
- routes/discussionVote.js
- routes/reports.js
made at the request of someone so they dont have to http spam /shrug
> add websocket for content review creation

- src/components/users/BnActivity.vue
- src/components/users/info/NatSubgroupToggle.vue
- src/pages/GroupHistoryPage.vue
- src/sass/app.scss
- views/index.hbs
triangles bg makes the whole site look less boring imo, worth a try
> some minor cleanups

- helpers/automation.js
- helpers/discord.js
- helpers/discord/getRoles.js
- helpers/discord/getWebhook.js
- routes/bnApp.js
- routes/debug.js
- routes/evaluations/appEval.js
- routes/index.js
- src/components/debugModal/DebugModalSessionEditor.vue
- src/components/evaluations/card/CardHeader.vue
- src/components/evaluations/card/EvaluationCard.vue
- src/components/evaluations/info/DiscussionInfo.vue
- src/components/evaluations/info/EvaluationInfo.vue
- src/components/evaluations/info/applications/EvaluationIsSecurityChecked.vue
- src/components/evaluations/info/common/FeedbackInfo.vue
- src/components/settingsModal/SettingsModalLanguages.vue
- webhooks.example.json
> sec check webhook

- helpers/util.js
- routes/bnApp.js
- routes/users/users.js
- src/bootstrap.js
- src/components/evaluations/EvaluationResults.vue
- src/components/evaluations/info/applications/EnableBnEvaluatorsChatMessage.vue
- src/components/qualityAssurance/Leaderboard.vue
- src/components/settingsModal/SettingsModalModeEvaluations.vue
- src/components/users/info/NextEvaluation.vue
- src/components/users/info/Resign.vue
- src/components/users/info/UserGroupToggle.vue
- src/mixins/evaluations.js
- src/pages/ApplicationSubmission.vue
- src/pages/Home.vue
- src/pages/ModRequests.vue
i loathed seeing/writing `${mode == 'osu' ? 'osu!' : 'osu!' + mode}` over and over
> add formatmode filter

- routes/users/users.js
- src/components/FilterBox.vue
- src/components/evaluations/info/common/EvaluationIsReviewed.vue
- src/components/evaluations/info/common/ProgressBar.vue
- src/components/users/info/NextEvaluation.vue
- src/pages/ApplicationSubmission.vue
- src/sass/_variables.scss
> bn app/eval progress bar

- README.md
- app.js
- routes/groupHistory.js
- routes/interOp.js
- src/App.vue
- src/components/vetoes/info/MediationInput.vue
- src/pages/GroupHistoryPage.vue
- src/store/http.js
- src/store/main.js
mg inspired me to do this
having it this way is more correct + we no longer have to worry about route conflicts between front and back
also includes some interop cleanups
> [!IMPORTANT]
> - [ ] update bnsite's osu! oauth client callback url
> use /api route for backend

- routes/vetoes.js
> re-enable veto messages

- src/bootstrap.js
- src/components/debugModal/DebugModalSessionEditor.vue
- src/components/debugModal/DebugModalUserInfo.vue
- src/components/evaluations/TrialInstructions.vue
- src/components/evaluations/info/EvaluationInfo.vue
- src/components/home/UserInfo.vue
- src/components/users/UserInfo.vue
- src/pages/AppEvalPage.vue
- src/pages/BnEvalPage.vue
- src/sass/_variables.scss
- src/sass/app.scss
the apps not loading thing was painful to spot as i was investigating Literally Everything Else lol
(also enabled `code blocks` and quote blocks for markdown and added bn evalers handbook per nat request)
> bn evaler fixes

- models/evaluations/evaluation.js
- models/interfaces/user.ts
- models/user.js
- routes/evaluations/bnEval.js
- routes/users/users.js
- src/components/evaluations/info/EvaluationInfo.vue
- src/components/evaluations/info/currentBns/SubjectiveFeedbackStatus.vue
- src/components/settingsModal/SettingsModal.vue
- src/components/settingsModal/SettingsModalEvaluator.vue
- src/components/settingsModal/SettingsModalSubjectiveEvalFeedback.vue
per osu! nat request
adds a settings thingy that's visible to only osu! BNs
which will display this info in eval cards
> subjective eval feedback toggle

- src/components/evaluations/info/common/ProgressBar.vue
> evalaution -> evaluation

- src/components/home/UserInfo.vue
> fix `isEditing` state visually not resetting when switching between homepage userpages

- routes/vetoes.js
- src/components/vetoes/info/MediationInput.vue
not sure why it's been like this for so long..
> make mediation comments mandatory

- routes/vetoes.js
- src/components/vetoes/VetoInfo.vue
- src/components/vetoes/info/AdminButtons.vue
- src/components/vetoes/info/Context.vue
- src/components/vetoes/info/Mediations.vue
- src/components/vetoes/info/VoteStats.vue
apparently last update broke public display so this fixes it
also makes stats properly tied to mediation visibility
> more fixes for veto info page

- routes/documentation.js
- src/components/discussion/info/MediatorOptions.vue
- src/components/evaluations/EvaluationResults.vue
- src/pages/ReportSubmission.vue
- src/sass/_variables.scss
> some internal requests

- src/App.vue
- src/sass/_custom.scss
Hivie did some restyling a couple days ago. On bigger monitors the glow effect he made starts to behave quite strange. This PR adjusted this so it is more aligned with the osu site which it was based on.
Before:
After:
> Nav bar restyle

- src/components/vetoes/info/MediationResponse.vue
> Revert "pain (in production)"

- src/components/evaluations/EvaluationResults.vue
- src/components/evaluations/info/common/EvaluationMessages.vue
regression from the march update, people are still misunderstanding
> update wording about eval outcome

- helpers/osu.js
- routes/dataCollection.js
- src/components/dataCollection/SyncEvents.vue
- src/mixins/evaluations.js
- src/pages/DataCollectionPage.vue
- src/pages/VetoesPage.vue
we can finally restore missing aiess noms/dqs 🎉
> add ability to sync missing beatmapset events

- src/components/vetoes/VetoInfo.vue
remnant from previous system that became an inconvenience
> expose admin buttons to all NATs in active mediations

- routes/users/users.js
- src/components/users/UniqueMapperStats.vue
- src/components/users/VibeCheckStats.vue
- src/pages/UsersPage.vue
made this for stats gathering https://discord.com/channels/90072389919997952/1305649753584963734/1306034063894777929, nice to keep around in case we need it again later
> add unique mapper stats tool

- helpers/scrap.js
> update bn activity reqs for nat

- helpers/scrap.js
theoretically makes sense but untested, i guess we'll know tomorrow
> proper consideration for nat noms pre-activity change

- helpers/util.js
- routes/dataCollection.js
Talked about this already with Hivie, it currently gives the following error when syncing osu!catch beatmaps:
> Fixed an issue where catch mapsets couldn't be synced

- src/components/users/info/Duration.vue
> also update nat duration section

- helpers/automation.js
> temporarily clear users who are eligible for a 100 nom badge

- helpers/automation.js
> Revert "temporarily clear users who are eligible for a 100 nom badge"

- src/components/evaluations/card/CardHeader.vue
- src/components/evaluations/card/EvaluationCard.vue
> add card icon for mock evals enabled + fix icon alignment
